### ISSUE TITLE
Error: duplicate name 'GenerateGmapSignedUrlOutProto' in Namespace .DumpProtos

### ISSUE THREAD

**Issue by PartTimeJS** [Furtif/POGOProtos#34]
Seeing duplicate object when parsing the proto file. I get this on raw_protos.proto but not in base.proto. Just started with this version. 

```
[
  Error: duplicate name 'GenerateGmapSignedUrlOutProto' in Namespace .DumpProtos
      at Namespace.add (...\node_modules\protobufjs\src\namespace.js:239:23)      
      at parseType (...\node_modules\protobufjs\src\parse.js:344:16)
      at parseCommon (...\node_modules\protobufjs\src\parse.js:259:17)
      at parse ...\node_modules\protobufjs\src\parse.js:731:21)
      at process (...\node_modules\protobufjs\src\root.js:117:30)
      at ...\node_modules\protobufjs\src\root.js:184:17
      at fetchReadFileCallback ...\Pokebot\node_modules\@protobufjs\fetch\index.js:51:19)
      at FSReqCallback.readFileAfterClose [as oncomplete] (internal/fs/read_file_context.js:63:3)
]

**Comment by Furtif** [comment]
one is GenerateGmapSignedUrlOutProto or GenerateGmapSignedUrlProto other is TitanGenerateGmapSignedUrlOutProto

**Comment by Furtif** [comment]
titan https://github.com/Furtif/POGOProtos/blob/master/base/base.proto#L15584
